
server.port=8081


spring.datasource.url=jdbc:h2:mem:testdb
spring.h2.console.enabled=true
spring.jpa.defer-datasource-initialization=true

eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka


resilience4j.retry.instances.sample-api.max-attempts=5
#If the service still fails on the 5th attempt, the system will finally throw an exception to the caller
resilience4j.retry.instances.sample-api.wait-duration=1s
#waits before attempting a retry
resilience4j.retry.instances.sample-api.enable-exponential-backoff=true
#the wait time increases after each failure
#1s â 2s â 4s â 8s â 16s

#The circuit will only open if 9 out of 10 requests fail.
resilience4j.circuitbreaker.instances.default.failure-rate-threshold=90

#in 10 s only allow 2 request
resilience4j.ratelimiter.instances.default.limit-for-period=2
resilience4j.ratelimiter.instances.default.limit-refresh-period=10s

# concurrent same time only 2 req allow
resilience4j.bulkhead.instances.default.max-concurrent-calls=2


#
# 1. New property name for enabling export (Renamed in 4.0)
#management.tracing.export.enabled=true

# 2. Set sampling to 100% for testing (so you see every request in Zipkin)
management.tracing.sampling.probability=1.0

# 3. Zipkin endpoint (ensure this matches your running Zipkin container)
#management.zipkin.tracing.endpoint=http://localhost:9411/api/v2/spans

# 4. REQUIRED: Enable the observation registry for web requests
#management.observations.http.server.requests.enabled=true
